apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongodb
    labels:
        app: guestbook
        tier: backend
spec:
    selector:
        matchLabels:
            app: guestbook
            tier: backend
    replicas: 1
    template:
        metadata:
            labels:
                app: guestbook
                tier: backend
        spec:
            containers:
                - name: mongodb
                  image: mongo:4.2
                  args:
                      - --bind_ip
                      - 0.0.0.0
                  resources:
                      requests:
                          cpu: 0.1
                          memory: 100Mi
                  ports:
                      - containerPort: 27017
