apiVersion: v1
kind: Service
metadata:
    name: mongo
    labels:
        app: guestbook
        tier: backend
spec:
    selector:
        app: guestbook
        tier: backend
    ports:
        - port: 27017
          protocol: TCP
          targetPort: 27017
