apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysqldb10
    labels:
        volume: mysqldb-volume10
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: ""
    selector:
        matchLabels:
            volume: mysqldb-volume10
