apiVersion: v1
kind: Pod
metadata:
    name: kuard
spec:
    containers:
        - image: gcr.io/k8s-vr-2021/kuard-amd64:blue
          name: kuard
          resources:
              cpu: "500m"
              memory: "128Mi"
          ports:
              - containerPort: 8080
                name: http
                protocol: TCP
