apiVersion: v1
kind: Service
metadata:
    name: alpaca-prod
    labels:
        app: alpaca
        env: prod
        version: 1.0.0
spec:
    selector:
        app: alpaca
    type: LoadBalancer
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
