apiVersion: v1
kind: Service
metadata:
    name: bandicoot-prod
    labels:
        app: bandicoot
        env: prod
        version: 1.0.0
spec:
    selector:
        app: bandicoot
    type: LoadBalancer
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
