apiVersion: apps/v1
kind: Deployment
metadata:
    name: sa-logic
    labels:
        app: sa
        component: logic
spec:
    selector:
        matchLabels:
            app: sa
            component: logic
    replicas: 2
    minReadySeconds: 15
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: sa
                component: logic
        spec:
            containers:
                - name: sa-logic
                  image: rinormaloku/sentiment-analysis-logic:feedback
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5000
