apiVersion: v1
kind: Pod
metadata:
    name: kuard
spec:
    volumes:
        - name: "kuard-data"
          hostPath:
              path: "/var/lib/kuard"
    containers:
        - image: gcr.io/k8s-vr-2021/kuard-amd64:blue
          name: kuard
          ports:
              - containerPort: 8080
                name: http
                protocol: TCP
          resources:
              requests:
                  cpu: "0.5"
                  memory: "128Mi"
              limits:
                  cpu: "1"
                  memory: "256Mi"
          volumeMounts:
              - mountPath: "/data"
                name: "kuard-data"
          livenessProbe:
              httpGet:
                  path: /healthy
                  port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 30
              failureThreshold: 3
          readinessProbe:
              httpGet:
                  path: /ready
                  port: 8080
              initialDelaySeconds: 30
              timeoutSeconds: 1
              periodSeconds: 30
              failureThreshold: 3
