apiVersion: v1
kind: Service
metadata:
    name: sa-frontend-lb
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: sa
        tier: frontend
