apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysqldb
    labels:
        volume: mysqldb-volume
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 1Gi
    nfs:
        server: 10.138.0.28
        path: "/share"
