apiVersion: apps/v1
kind: Deployment
metadata:
    name: sa-frontend
    labels:
        app: sa
        tier: frontend
spec:
    selector:
        matchLabels:
            app: sa
            tier: frontend
    replicas: 2
    minReadySeconds: 15
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: sa
                tier: frontend
            annotations:
                kubernetes.io/change-cause: "Change image version (latest -> green)"
        spec:
            containers:
                - name: sa-frontend
                  image: rinormaloku/sentiment-analysis-frontend:green
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
