apiVersion: v1
kind: Service
metadata:
    name: sa-webapp-lb
spec:
    type: LoadBalancer
    ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
    selector:
        app: sa
        tier: webapp
